name: Create Release
"on":
  push:
    branches:
      - main
jobs:
  create-releas:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - name: Sigin to git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Calculate build number
        id: build-number
        run: |
          BUILD_NUMBER=$GITHUB_RUN_NUMBER
          echo "Build number: $BUILD_NUMBER"
          echo ::set-output name=BUILD_NUMBER::$BUILD_NUMBER

      - name: Update manfiest verison behavior
        run: echo $(cat borderbp/manifest.json | jq '.header.version = [0, 0, ${{ steps.build-number.outputs.BUILD_NUMBER }}]') > borderbp/manifest.json
      - name: Update manfiest verison texture
        run: echo $(cat borderrp/manifest.json | jq '.header.version = [0, 0, ${{ steps.build-number.outputs.BUILD_NUMBER }}]') > borderrp/manifest.json
      - name: Update manfiest verison texture within behavior
        run: echo $(cat borderbp/manifest.json | jq '.dependencies[0].version = [0, 0, ${{ steps.build-number.outputs.BUILD_NUMBER }}]') > borderbp/manifest.json

      - name: Update manifest name behavior
        uses: jossef/action-set-json-field@v1
        with:
          file: borderbp/manifest.json
          field: header.description
          value: New Caledonia Border Addon 0.0.${{ steps.build-number.outputs.BUILD_NUMBER }}
      - name: Update manifest name texture
        uses: jossef/action-set-json-field@v1
        with:
          file: borderrp/manifest.json
          field: header.description
          value: New Caledonia Border Addon 0.0.${{ steps.build-number.outputs.BUILD_NUMBER }}

      - name: manifest update
        run: |
          git add "borderbp/manifest.json"
          git add "borderrp/manifest.json"
          git commit -m "0.0.${{ steps.build-number.outputs.BUILD_NUMBER }}"

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Push manifest commit
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.extract_branch.outputs.branch }}

      - name: Compress Json
        run: |
          chmod +x compress-json.sh
          ./compress-json.sh

      # behavior zip
      - uses: vimtor/action-zip@v1
        with:
          files: borderbp/
          dest: borderbp.0.0.${{ steps.build-number.outputs.BUILD_NUMBER }}.zip
      - uses: vimtor/action-zip@v1
        with:
          files: borderbp/
          dest: borderbp.0.0.${{ steps.build-number.outputs.BUILD_NUMBER }}.mcpack
      - name: Upload .zip as artifact
        uses: actions/upload-artifact@v2
        with:
          name: borderbp.0.0.${{ steps.build-number.outputs.BUILD_NUMBER }}.zip
          path: borderbp.0.0.${{ steps.build-number.outputs.BUILD_NUMBER }}.zip
          if-no-files-found: error
      - name: Upload .mcpack as artifact
        uses: actions/upload-artifact@v2
        with:
          name: borderbp.0.0.${{ steps.build-number.outputs.BUILD_NUMBER }}.mcpack
          path: borderbp.0.0.${{ steps.build-number.outputs.BUILD_NUMBER }}.mcpack
          if-no-files-found: error

      # texture zip
      - uses: vimtor/action-zip@v1
        with:
          files: borderrp/
          dest: borderrp.0.0.${{ steps.build-number.outputs.BUILD_NUMBER }}.zip
      - uses: vimtor/action-zip@v1
        with:
          files: borderrp/
          dest: borderrp.0.0.${{ steps.build-number.outputs.BUILD_NUMBER }}.mcpack
      - name: Upload .zip as artifact
        uses: actions/upload-artifact@v2
        with:
          name: borderrp.0.0.${{ steps.build-number.outputs.BUILD_NUMBER }}.zip
          path: borderrp.0.0.${{ steps.build-number.outputs.BUILD_NUMBER }}.zip
          if-no-files-found: error
      - name: Upload .mcpack as artifact
        uses: actions/upload-artifact@v2
        with:
          name: borderrp.0.0.${{ steps.build-number.outputs.BUILD_NUMBER }}.mcpack
          path: borderrp.0.0.${{ steps.build-number.outputs.BUILD_NUMBER }}.mcpack
          if-no-files-found: error

      # Compine
      - uses: vimtor/action-zip@v1
        with:
          files: borderbp.0.0.${{ steps.build-number.outputs.BUILD_NUMBER }}.zip borderrp.0.0.${{ steps.build-number.outputs.BUILD_NUMBER }}.zip
          dest: border.0.0.${{ steps.build-number.outputs.BUILD_NUMBER }}.zip
      - uses: vimtor/action-zip@v1
        with:
          files: borderbp.0.0.${{ steps.build-number.outputs.BUILD_NUMBER }}.mcpack borderrp.0.0.${{ steps.build-number.outputs.BUILD_NUMBER }}.mcpack
          dest: border.0.0.${{ steps.build-number.outputs.BUILD_NUMBER }}.mcaddon
      - name: Upload .zip as artifact
        uses: actions/upload-artifact@v2
        with:
          name: border.0.0.${{ steps.build-number.outputs.BUILD_NUMBER }}.zip
          path: border.0.0.${{ steps.build-number.outputs.BUILD_NUMBER }}.zip
          if-no-files-found: error
      - name: Upload .mcpack as artifact
        uses: actions/upload-artifact@v2
        with:
          name: border.0.0.${{ steps.build-number.outputs.BUILD_NUMBER }}.mcaddon
          path: border.0.0.${{ steps.build-number.outputs.BUILD_NUMBER }}.mcaddon
          if-no-files-found: error

      - name: Puts the release on GitHub
        uses: ncipollo/release-action@v1
        with:
          artifacts: "borderbp.0.0.${{ steps.build-number.outputs.BUILD_NUMBER }}.zip, borderbp.0.0.${{ steps.build-number.outputs.BUILD_NUMBER }}.mcpack, borderrp.0.0.${{ steps.build-number.outputs.BUILD_NUMBER }}.zip, borderrp.0.0.${{ steps.build-number.outputs.BUILD_NUMBER }}.mcpack, border.0.0.${{ steps.build-number.outputs.BUILD_NUMBER }}.zip, border.0.0.${{ steps.build-number.outputs.BUILD_NUMBER }}.mcaddon"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: 0.0.${{ steps.build-number.outputs.BUILD_NUMBER }}
          name: 0.0.${{ steps.build-number.outputs.BUILD_NUMBER }} New Caledonia Border Addon
          prerelease: true
