name: Create Release
'on':
  push:
    branches:
      - main
jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      
      - name: Calculate build number
        id: build-number
        run: |
          BUILD_NUMBER=$(($GITHUB_RUN_NUMBER)) #to stay above jenkins
          echo "Build number: $BUILD_NUMBER"
          echo ::set-output name=BUILD_NUMBER::$BUILD_NUMBER
      
      - uses: vimtor/action-zip@v1
        with:
          files: borderbp/
          dest: borderbp.0.0.${{ steps.build-number.outputs.BUILD_NUMBER }}.zip
      - uses: vimtor/action-zip@v1
        with:
          files: borderbp/
          dest: borderbp.0.0.${{ steps.build-number.outputs.BUILD_NUMBER }}.mcpack
          
      - name: Puts the release on GitHub
        uses: ncipollo/release-action@v1
        with:
          artifacts: "borderbp.zip, borderbp.mcpack"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: 0.0.${{ steps.build-number.outputs.BUILD_NUMBER }}
          name: 0.0.${{ steps.build-number.outputs.BUILD_NUMBER }} New Caledonia Border Addon 
          prerelease: true
