name: Create Release
"on":
  push:
    branches:
      - main
jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - name: Sigin to git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Generate build number
        id: build-number
        uses: einaregilsson/build-number@v3
        with:
          token: ${{secrets.github_token}}

      - name: Update manfiest verison behavior
        run: echo $(cat borderbp/manifest.json | jq '.header.version = [0, 2, ${{ steps.build-number.outputs.build_number }}]') > borderbp/manifest.json
      - name: Update manfiest verison texture
        run: echo $(cat borderrp/manifest.json | jq '.header.version = [0, 2, ${{ steps.build-number.outputs.build_number }}]') > borderrp/manifest.json
      - name: Update manfiest verison texture within behavior
        run: echo $(cat borderbp/manifest.json | jq '.dependencies[0].version = [0, 2, ${{ steps.build-number.outputs.build_number }}]') > borderbp/manifest.json

      - name: Update manifest name behavior
        uses: jossef/action-set-json-field@v1
        with:
          file: borderbp/manifest.json
          field: header.description
          value: New Caledonia Border Addon 0.2.${{ steps.build-number.outputs.build_number }}
      - name: Update manifest name texture
        uses: jossef/action-set-json-field@v1
        with:
          file: borderrp/manifest.json
          field: header.description
          value: New Caledonia Border Addon 0.2.${{ steps.build-number.outputs.build_number }}

      - name: manifest update
        run: |
          git add "borderbp/manifest.json"
          git add "borderrp/manifest.json"
          git commit -m "0.2.${{ steps.build-number.outputs.build_number }}"

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Push manifest commit
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.extract_branch.outputs.branch }}

      #- name: Compress Json
      #  run: |
      #    chmod +x compress-json.sh
      #    ./compress-json.sh

      # behavior zip
      - uses: vimtor/action-zip@v1
        with:
          files: borderbp/
          dest: borderbp.0.2.${{ steps.build-number.outputs.build_number }}.zip
      - uses: vimtor/action-zip@v1
        with:
          files: borderbp/
          dest: borderbp.0.2.${{ steps.build-number.outputs.build_number }}.mcpack
      - name: Upload .zip as artifact
        uses: actions/upload-artifact@v2
        with:
          name: borderbp.0.2.${{ steps.build-number.outputs.build_number }}.zip
          path: borderbp.0.2.${{ steps.build-number.outputs.build_number }}.zip
          if-no-files-found: error
      - name: Upload .mcpack as artifact
        uses: actions/upload-artifact@v2
        with:
          name: borderbp.0.2.${{ steps.build-number.outputs.build_number }}.mcpack
          path: borderbp.0.2.${{ steps.build-number.outputs.build_number }}.mcpack
          if-no-files-found: error

      # texture zip
      - uses: vimtor/action-zip@v1
        with:
          files: borderrp/
          dest: borderrp.0.2.${{ steps.build-number.outputs.build_number }}.zip
      - uses: vimtor/action-zip@v1
        with:
          files: borderrp/
          dest: borderrp.0.2.${{ steps.build-number.outputs.build_number }}.mcpack
      - name: Upload .zip as artifact
        uses: actions/upload-artifact@v2
        with:
          name: borderrp.0.2.${{ steps.build-number.outputs.build_number }}.zip
          path: borderrp.0.2.${{ steps.build-number.outputs.build_number }}.zip
          if-no-files-found: error
      - name: Upload .mcpack as artifact
        uses: actions/upload-artifact@v2
        with:
          name: borderrp.0.2.${{ steps.build-number.outputs.build_number }}.mcpack
          path: borderrp.0.2.${{ steps.build-number.outputs.build_number }}.mcpack
          if-no-files-found: error

      # Compine
      - uses: vimtor/action-zip@v1
        with:
          files: borderbp.0.2.${{ steps.build-number.outputs.build_number }}.zip borderrp.0.2.${{ steps.build-number.outputs.build_number }}.zip
          dest: border.0.2.${{ steps.build-number.outputs.build_number }}.zip
      - uses: vimtor/action-zip@v1
        with:
          files: borderbp.0.2.${{ steps.build-number.outputs.build_number }}.zip borderrp.0.2.${{ steps.build-number.outputs.build_number }}.zip
          dest: border.0.2.${{ steps.build-number.outputs.build_number }}.mcaddon
      - name: Upload .zip as artifact
        uses: actions/upload-artifact@v2
        with:
          name: border.0.2.${{ steps.build-number.outputs.build_number }}.zip
          path: border.0.2.${{ steps.build-number.outputs.build_number }}.zip
          if-no-files-found: error
      - name: Upload .mcpack as artifact
        uses: actions/upload-artifact@v2
        with:
          name: border.0.2.${{ steps.build-number.outputs.build_number }}.mcaddon
          path: border.0.2.${{ steps.build-number.outputs.build_number }}.mcaddon
          if-no-files-found: error

      - name: Puts the release on GitHub
        uses: ncipollo/release-action@v1
        with:
          artifacts: "borderbp.0.2.${{ steps.build-number.outputs.build_number }}.zip, borderbp.0.2.${{ steps.build-number.outputs.build_number }}.mcpack, borderrp.0.2.${{ steps.build-number.outputs.build_number }}.zip, borderrp.0.2.${{ steps.build-number.outputs.build_number }}.mcpack, border.0.2.${{ steps.build-number.outputs.build_number }}.zip, border.0.2.${{ steps.build-number.outputs.build_number }}.mcaddon"
          #artifacts: "border.0.2.${{ steps.build-number.outputs.build_number }}.zip, border.0.2.${{ steps.build-number.outputs.build_number }}.mcaddon"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: 0.2.${{ steps.build-number.outputs.build_number }}
          name: 0.2.${{ steps.build-number.outputs.build_number }} New Caledonia Border Addon
          prerelease: true
